export const DECKS_LIST__REQUEST = 'DECKS_LIST__REQUEST';
export const DECKS_LIST__SUCCESS = 'DECKS_LIST__SUCCESS';
export const DECKS_LIST__ERROR = 'DECKS_LIST__ERROR';

export const DECKS_FORM__CHANGE = 'DECKS_FORM__CHANGE';
export const DECKS_FORM__REQUEST = 'DECKS_FORM__REQUEST';
export const DECKS_FORM__SUCCESS = 'DECKS_FORM__SUCCESS';
export const DECKS_FORM__ERROR = 'DECKS_FORM__ERROR';

export const DECKS_VIEW__REQUEST = 'DECKS_VIEW__REQUEST';
export const DECKS_VIEW__SUCCESS = 'DECKS_VIEW__SUCCESS';
export const DECKS_VIEW__ERROR = 'DECKS_VIEW__ERROR';
