export const CARDS_FORM_CHANGE = 'CARDS_FORM_CHANGE';
export const CARDS_FORM_CHANGE_COLOR = 'CARDS_FORM_CHANGE_COLOR';
export const CARDS_SET_QUERY = 'CARDS_SET_QUERY';

export const CARDS_REQUEST = 'CARDS_REQUEST';
export const CARDS_SUCCESS = 'CARDS_SUCCESS';
export const CARDS_ERROR = 'CARDS_ERROR';
export const CARDS_MORE = 'CARDS_MORE';
