export const DECK_VIEW__DECK__REQUEST = 'DECK_VIEW__DECK__REQUEST';
export const DECK_VIEW__DECK__SUCCESS = 'DECK_VIEW__DECK__SUCCESS';
export const DECK_VIEW__DECK__ERROR = 'DECK_VIEW__DECK__ERROR';

export const DECK_VIEW__NAME__CHANGE = 'DECK_VIEW__NAME__CHANGE';
export const DECK_VIEW__ARRAY__CHANGE = 'DECK_VIEW__ARRAY__CHANGE';
