export const CARDS_FORM_SUBMIT = 'CARDS_FORM_SUBMIT';
export const CARDS_FORM_SET_PARAMS = 'CARDS_FORM_SET_PARAMS';
export const CARDS_FORM_CHANGE = 'CARDS_FORM_CHANGE';

export const CARDS_REQUEST = 'CARDS_REQUEST';
export const CARDS_SUCCESS = 'CARDS_SUCCESS';
export const CARDS_ERROR = 'CARDS_ERROR';
