export const CARDS_FORM__SUBMIT = 'CARDS_FORM__SUBMIT';
export const CARDS_FORM__SET_PARAMS = 'CARDS_FORM__SET_PARAMS';
export const CARDS_FORM__CHANGE = 'CARDS_FORM__CHANGE';
export const CARDS_FORM__MORE = 'CARDS_FORM__MORE';

export const CARDS_LIST__REQUEST = 'CARDS_LIST__REQUEST';
export const CARDS_LIST__SUCCESS = 'CARDS_LIST__SUCCESS';
export const CARDS_LIST__ERROR = 'CARDS_LIST__ERROR';

export const CARDS_ITEM__ADD_REQUEST = 'CARDS_ITEM__ADD_REQUEST';
export const CARDS_ITEM__ADD_SUCCESS = 'CARDS_ITEM__ADD_SUCCESS';
export const CARDS_ITEM__ADD_ERROR = 'CARDS_ITEM__ADD_ERROR';
