export const GAMES_FORM__SUBMIT = 'GAMES_FORM__SUBMIT';
export const GAMES_FORM__SET_PARAMS = 'GAMES_FORM__SET_PARAMS';
export const GAMES_FORM__CHANGE = 'GAMES_FORM__CHANGE';
export const GAMES_FORM__MORE = 'GAMES_FORM__MORE';

export const GAMES_LIST__REQUEST = 'GAMES_LIST__REQUEST';
export const GAMES_LIST__SUCCESS = 'GAMES_LIST__SUCCESS';
export const GAMES_LIST__ERROR = 'GAMES_LIST__ERROR';
